backend:
  name: git-gateway
  branch: main

# Media files
media_folder: "src/images"    # Store uploaded images here
public_folder: "/images"      # Path used in the generated site
media_library: {}             # Required, use local media library

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/blog"        # Folder where posts are stored
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "list", default: ["post"] }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }