backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
  media_folder: "images" # Media files will be stored in the repo under images/uploads
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "src/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
  - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
  - { label: "Title", name: "title", widget: "string" }
  - { label: "Author", name: "author", widget: "string" }
  - { label: "Date", name: "date", widget: "datetime" }
  - { label: "Tags", name: "tags", widget: "list", default: ["post"] }
  - { label: "Featured Image", name: "image", widget: "image" }
  - { label: "Image Alt Text", name: "imageAlt", widget: "string" }
  - { label: "Description", name: "description", widget: "text" }
  - { label: "Rating (1-5)", name: "rating", widget: "number" }
  - { label: "Body", name: "body", widget: "markdown" }
      ---
title: "fourth post"
author: "Mark Cusack"
date: 2026-02-09
tags: ["post", "featured"]
image: /images/bigfoot.jpg
imageAlt: this is a test
description: "A simple guide to writing blog posts in Markdown."
---
